Last login: Thu May 23 11:28:57 on ttys001
O-02976-MAC:~ adrian.candos$ ls
01-02-afterreview.pl  	Perl-13.pl			adriancdperu.pem		myfirstmodule
02.pl				Perl-14.pl			apollo				myhash.pl
03-06-afterreview.pl		Perl-15.pl			awawa.pl			obfu.pl
1-03.pl				Perl-16.pl			bite_counter.pl			pages.conf
1-Q03.pl			Perl-17.pl			byte_counter.pl			paruparu03.pl
1-Q04.pl			Perl-18.pl			callback.pl			paruparu04.pl
1-Q05.pl			Perl-19.pl			callback_improved.pl		paruparu05.pl
1-Q06.pl			Perl-2.pl			callback_improved2.pl		paruparu06.pl
1review.pl			Perl-20.pl			callback_improved3.pl		paruparu07.pl
:e				Perl-21.pl			castaways.log			paruparu1.pl
BBS				Perl-212.pl			cat-install			paruparu2.pl
CatalystTutorial		Perl-22.pl			checking.pl			pattern-tester.pl
CatalystTutorial.tar.gz		Perl-23.pl			comment				perl5
Desktop				Perl-25.pl			connection.pl			perlgames
Documents			Perl-30.pl			connection1.pl			playingwitharrays.pl
Downloads			Perl-6-Connection.pl		curly				problems01-02.pl
Dropbox				Perl-7.pl			cws2				problems03-06.pl
ElDorado1.pl			Perl-8.pl			db01.pl				quick.pl
ElDorado2.pl			Perl-9.pl			db1.sql				quiz1review.pl
Gear01.pl			Perl-99.pl			dirty.pl			radious.pl
Ginger				Perl-OSType-1.003		dorado1.pl			repo01
Golden1.pl			Perlito01.pl			ejercicio1.pl			script.pl
Golden2.pl			Pictures			eldorado.pl			simple.sh
Hello-World			Public				gitnonterminal.sh		stats.pl
LOG				Q07.pl				hash.pl				table1.sql
Library				Q08.pl				hdfs2db.pl			test-more-cmp.pl
Lola				Q09.pl				hello_world			test.pl
MDCPanel.pm			Q10.pl				human.pem			test01.pl
MVC				Q11.pl				human.pl			test1.pl
March14-Array-elements-sum.pl	Q12.pl				human.pm			test2.pl
March14-Q02.pl			Q13.pl				importance-of-strict.pl		test2.pm
March14-Q03.pl			Q14.pl				jan-ken.pl			testa.pl
March15-01.pl			Q14new.pl			janken.pl			testa1.pl
March15-02.pl			Q15.pl				java-eclipse-thingies		twit
March15-03.pl			Q15new.pl			johnny				unejemplo.pl
Module-Build-0.4003		Q15newnew.pl			logfile				unixtime.pl
Movies				Saint.pl			logfile.txt			unixtime.plls
Music				Text-14.txt			lolipop				unomas.pl
MyFirstModule.pl		Text-Roro.txt			match.pl			usehuman.pl
MyFirstModule.pm		Vagrantfile			mdcpanel_logout.html		vagrant_getting_started
PEARL1.pl			VirtualBox VMs			moe				weirdcode1.pl
Perl-10.pl			a.pl				multidevice_cpanel.html		weirdcode2.pl
Perl-11.pl			a0fewqqwrm.pl			my_first_test.pl
Perl-12.pl			adriancdperu-for-practicing.pem	my_mojolicious_app
O-02976-MAC:~ adrian.candos$ amon2-setup.pl forexgame
-- Running flavor: Basic --
[Flavor::Basic] Loading asset: jQuery
[Flavor::Basic] Loading asset: Bootstrap
[Flavor::Basic] Loading asset: ES5Shim
[Flavor::Basic] Loading asset: MicroTemplateJS
[Flavor::Basic] Loading asset: StrftimeJS
[Flavor::Basic] Loading asset: SprintfJS
[Flavor::Basic] Loading asset: MicroLocationJS
[Flavor::Basic] Loading asset: MicroDispatcherJS
[Flavor::Minimum] writing lib/forexgame.pm
[Flavor::Basic] writing tmpl/index.tt
[Flavor::Basic] writing tmpl/include/layout.tt
[Flavor::Basic] writing tmpl/include/pager.tt
[Flavor::Basic] writing lib/forexgame/Web.pm
[Flavor::Basic] writing lib/forexgame/Web/Dispatcher.pm
[Flavor::Minimum] writing lib/forexgame/Web/View.pm
[Flavor::Minimum] writing lib/forexgame/Web/ViewFunctions.pm
[Flavor::Minimum] writing Build.PL
[Flavor::Minimum] writing cpanfile
[Flavor::Minimum] writing t/00_compile.t
[Flavor::Minimum] writing t/01_root.t
[Flavor::Minimum] writing t/02_mech.t
[Flavor::Minimum] writing t/Util.pm
[Flavor::Minimum] writing xt/01_pod.t
[Flavor::Basic] writing static/js/jquery-1.9.1.min.js
[Flavor::Basic] writing static/bootstrap/css/bootstrap.min.css
[Flavor::Basic] writing static/bootstrap/css/bootstrap.css
[Flavor::Basic] writing static/bootstrap/img/glyphicons-halflings-white.png
[Flavor::Basic] writing static/bootstrap/css/bootstrap-responsive.min.css
[Flavor::Basic] writing static/bootstrap/img/glyphicons-halflings.png
[Flavor::Basic] writing static/bootstrap/css/bootstrap-responsive.css
[Flavor::Basic] writing static/bootstrap/js/bootstrap.min.js
[Flavor::Basic] writing static/bootstrap/js/bootstrap.js
[Flavor::Basic] writing static/js/es5-shim.min.js
[Flavor::Basic] writing static/js/micro_template.js
[Flavor::Basic] writing static/js/strftime.js
Wide character in print at /Library/Perl/5.12/Amon2/Setup/Flavor.pm line 95.
[Flavor::Basic] writing static/js/sprintf-0.7-beta1.js
[Flavor::Basic] writing static/js/micro-location.js
[Flavor::Basic] writing static/js/micro_dispatcher.js
[Flavor::Basic] writing static/img/.gitignore
[Flavor::Basic] writing static/robots.txt
[Flavor::Basic] writing static/js/main.js
[Flavor::Basic] writing static/css/main.css
[Flavor::Basic] writing app.psgi
[Flavor::Basic] writing lib/forexgame.pm
[Flavor::Basic] writing lib/forexgame/Web.pm
[Flavor::Basic] writing lib/forexgame/Web/Dispatcher.pm
[Flavor::Minimum] writing lib/forexgame/Web/View.pm
[Flavor::Basic] writing db/.gitignore
[Flavor::Basic] writing config/development.pl
[Flavor::Basic] writing config/deployment.pl
[Flavor::Basic] writing config/test.pl
[Flavor::Basic] writing sql/mysql.sql
[Flavor::Basic] writing sql/sqlite.sql
[Flavor::Basic] writing t/00_compile.t
[Flavor::Basic] writing xt/02_perlcritic.t
[Flavor::Basic] writing .gitignore
[Flavor::Basic] writing t/03_assets.t
[Flavor::Basic] writing .proverc
[Flavor::Basic] writing t/06_jslint.t
[Flavor::Basic] writing static/404.html
[Flavor::Basic] writing static/500.html
[Flavor::Basic] writing static/502.html
[Flavor::Basic] writing static/503.html
[Flavor::Basic] writing static/504.html
Initialized empty Git repository in /Users/adrian.candos/forexgame/.git/
[master (root-commit) 99c004b] initial import
 49 files changed, 10937 insertions(+)
 create mode 100644 .gitignore
 create mode 100644 .proverc
 create mode 100644 Build.PL
 create mode 100644 app.psgi
 create mode 100644 config/deployment.pl
 create mode 100644 config/development.pl
 create mode 100644 config/test.pl
 create mode 100644 cpanfile
 create mode 100644 db/.gitignore
 create mode 100644 lib/forexgame.pm
 create mode 100644 lib/forexgame/Web.pm
 create mode 100644 lib/forexgame/Web/Dispatcher.pm
 create mode 100644 lib/forexgame/Web/View.pm
 create mode 100644 lib/forexgame/Web/ViewFunctions.pm
 create mode 100644 sql/mysql.sql
 create mode 100644 sql/sqlite.sql
 create mode 100644 static/404.html
 create mode 100644 static/500.html
 create mode 100644 static/502.html
 create mode 100644 static/503.html
 create mode 100644 static/504.html
 create mode 100644 static/bootstrap/css/bootstrap-responsive.css
 create mode 100644 static/bootstrap/css/bootstrap-responsive.min.css
 create mode 100644 static/bootstrap/css/bootstrap.css
 create mode 100644 static/bootstrap/css/bootstrap.min.css
 create mode 100644 static/bootstrap/img/glyphicons-halflings-white.png
 create mode 100644 static/bootstrap/img/glyphicons-halflings.png
 create mode 100644 static/bootstrap/js/bootstrap.js
 create mode 100644 static/bootstrap/js/bootstrap.min.js
 create mode 100644 static/css/main.css
 create mode 100644 static/img/.gitignore
 create mode 100644 static/js/es5-shim.min.js
 create mode 100644 static/js/jquery-1.9.1.min.js
 create mode 100644 static/js/main.js
 create mode 100644 static/js/micro-location.js
 create mode 100644 static/js/micro_dispatcher.js
 create mode 100644 static/js/micro_template.js
 create mode 100644 static/js/sprintf-0.7-beta1.js
 create mode 100644 static/js/strftime.js
 create mode 100644 static/robots.txt
 create mode 100644 t/00_compile.t
 create mode 100644 t/01_root.t
 create mode 100644 t/02_mech.t
 create mode 100644 t/03_assets.t
 create mode 100644 t/06_jslint.t
 create mode 100644 t/Util.pm
 create mode 100644 tmpl/include/layout.tt
 create mode 100644 tmpl/include/pager.tt
 create mode 100644 tmpl/index.tt
 create mode 100644 xt/01_pod.t
 create mode 100644 xt/02_perlcritic.t
O-02976-MAC:~ adrian.candos$ ls
01-02-afterreview.pl		Perl-13.pl			adriancdperu.pem		my_mojolicious_app
02.pl				Perl-14.pl			apollo				myfirstmodule
03-06-afterreview.pl		Perl-15.pl			awawa.pl			myhash.pl
1-03.pl				Perl-16.pl			bite_counter.pl			obfu.pl
1-Q03.pl			Perl-17.pl			byte_counter.pl			pages.conf
1-Q04.pl			Perl-18.pl			callback.pl			paruparu03.pl
1-Q05.pl			Perl-19.pl			callback_improved.pl		paruparu04.pl
1-Q06.pl			Perl-2.pl			callback_improved2.pl		paruparu05.pl
1review.pl			Perl-20.pl			callback_improved3.pl		paruparu06.pl
:e				Perl-21.pl			castaways.log			paruparu07.pl
BBS				Perl-212.pl			cat-install			paruparu1.pl
CatalystTutorial		Perl-22.pl			checking.pl			paruparu2.pl
CatalystTutorial.tar.gz		Perl-23.pl			comment				pattern-tester.pl
Desktop				Perl-25.pl			connection.pl			perl5
Documents			Perl-30.pl			connection1.pl			perlgames
Downloads			Perl-6-Connection.pl		curly				playingwitharrays.pl
Dropbox				Perl-7.pl			cws2				problems01-02.pl
ElDorado1.pl			Perl-8.pl			db01.pl				problems03-06.pl
ElDorado2.pl			Perl-9.pl			db1.sql				quick.pl
Gear01.pl			Perl-99.pl			dirty.pl			quiz1review.pl
Ginger				Perl-OSType-1.003		dorado1.pl			radious.pl
Golden1.pl			Perlito01.pl			ejercicio1.pl			repo01
Golden2.pl			Pictures			eldorado.pl			script.pl
Hello-World			Public				forexgame			simple.sh
LOG				Q07.pl				gitnonterminal.sh		stats.pl
Library				Q08.pl				hash.pl				table1.sql
Lola				Q09.pl				hdfs2db.pl			test-more-cmp.pl
MDCPanel.pm			Q10.pl				hello_world			test.pl
MVC				Q11.pl				human.pem			test01.pl
March14-Array-elements-sum.pl	Q12.pl				human.pl			test1.pl
March14-Q02.pl			Q13.pl				human.pm			test2.pl
March14-Q03.pl			Q14.pl				importance-of-strict.pl		test2.pm
March15-01.pl			Q14new.pl			jan-ken.pl			testa.pl
March15-02.pl			Q15.pl				janken.pl			testa1.pl
March15-03.pl			Q15new.pl			java-eclipse-thingies		twit
Module-Build-0.4003		Q15newnew.pl			johnny				unejemplo.pl
Movies				Saint.pl			logfile				unixtime.pl
Music				Text-14.txt			logfile.txt			unixtime.plls
MyFirstModule.pl		Text-Roro.txt			lolipop				unomas.pl
MyFirstModule.pm		Vagrantfile			match.pl			usehuman.pl
PEARL1.pl			VirtualBox VMs			mdcpanel_logout.html		vagrant_getting_started
Perl-10.pl			a.pl				moe				weirdcode1.pl
Perl-11.pl			a0fewqqwrm.pl			multidevice_cpanel.html		weirdcode2.pl
Perl-12.pl			adriancdperu-for-practicing.pem	my_first_test.pl
O-02976-MAC:~ adrian.candos$ cd forexgame
O-02976-MAC:forexgame adrian.candos$ ls
Build.PL	config		db		sql		t		xt
app.psgi	cpanfile	lib		static		tmpl
O-02976-MAC:forexgame adrian.candos$ vim Build.PL

use strict;
use warnings;
use Module::Build;
use Module::CPANfile;

my $file = Module::CPANfile->load("cpanfile");
my $prereq = $file->prereq_specs;

my $build = Module::Build->subclass(
    code => q{
        sub ACTION_install {
            die "Do not install web application.\n";
        }

        # do not make blib.
        sub ACTION_code {
            my $self = shift;
            $self->depends_on('config_data');
        }

        # run prove
        sub ACTION_test {
            my $self = shift;
            my $tests = $self->find_test_files;

            require App::Prove;
            my $prove = App::Prove->new();
            $prove->process_args('-l', @$tests);
            $prove->run();
        }
    }
)->new(
    license              => 'unknown',
    dynamic_config       => 0,

    build_requires       => {
        $prereq->{build} ? %{$prereq->{build}->{requires}} : (),
        $prereq->{test} ? %{$prereq->{test}->{requires}} : (),
    },
    configure_requires   => {
        %{$prereq->{configure}->{requires}},
    },
"Build.PL" 60L, 1574C
